/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navbar`; params?: Router.UnknownInputParams; } | { pathname: `/screens/convert-points`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/buy-tokens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/job-approvals`; params?: Router.UnknownInputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/map`; params?: Router.UnknownInputParams; } | { pathname: `/screens/partner-products`; params?: Router.UnknownInputParams; } | { pathname: `/screens/post-job`; params?: Router.UnknownInputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownInputParams; } | { pathname: `/screens/user-management`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navbar`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/convert-points`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/buy-tokens`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/job-approvals`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/map`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/partner-products`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/post-job`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/user-management`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/navbar${`?${string}` | `#${string}` | ''}` | `/screens/convert-points${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/login-and-authetication/login${`?${string}` | `#${string}` | ''}` | `/login-and-authetication/signup${`?${string}` | `#${string}` | ''}` | `/screens/buy-tokens${`?${string}` | `#${string}` | ''}` | `/screens/dashboard${`?${string}` | `#${string}` | ''}` | `/screens/home${`?${string}` | `#${string}` | ''}` | `/screens/job-approvals${`?${string}` | `#${string}` | ''}` | `/screens/jobs${`?${string}` | `#${string}` | ''}` | `/screens/map${`?${string}` | `#${string}` | ''}` | `/screens/partner-products${`?${string}` | `#${string}` | ''}` | `/screens/post-job${`?${string}` | `#${string}` | ''}` | `/screens/profile${`?${string}` | `#${string}` | ''}` | `/screens/rewards${`?${string}` | `#${string}` | ''}` | `/screens/scan${`?${string}` | `#${string}` | ''}` | `/screens/user-management${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navbar`; params?: Router.UnknownInputParams; } | { pathname: `/screens/convert-points`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/buy-tokens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/job-approvals`; params?: Router.UnknownInputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/map`; params?: Router.UnknownInputParams; } | { pathname: `/screens/partner-products`; params?: Router.UnknownInputParams; } | { pathname: `/screens/post-job`; params?: Router.UnknownInputParams; } | { pathname: `/screens/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownInputParams; } | { pathname: `/screens/user-management`; params?: Router.UnknownInputParams; };
    }
  }
}
