/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/map`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/index`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/screens/map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../home.s/map`; params?: Router.UnknownOutputParams; } | { pathname: `/../home.s/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../home.s/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../home.s/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home`; params?: Router.UnknownOutputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/map`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../home.s/map${`?${string}` | `#${string}` | ''}` | `/../home.s/signup${`?${string}` | `#${string}` | ''}` | `/../home.s/index${`?${string}` | `#${string}` | ''}` | `/../home.s/login${`?${string}` | `#${string}` | ''}` | `/screens/home${`?${string}` | `#${string}` | ''}` | `/login-and-authetication/login${`?${string}` | `#${string}` | ''}` | `/screens/scan${`?${string}` | `#${string}` | ''}` | `/login-and-authetication/signup${`?${string}` | `#${string}` | ''}` | `/screens/jobs${`?${string}` | `#${string}` | ''}` | `/screens/rewards${`?${string}` | `#${string}` | ''}` | `/screens/map${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/map`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/index`; params?: Router.UnknownInputParams; } | { pathname: `/../home.s/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/scan`; params?: Router.UnknownInputParams; } | { pathname: `/login-and-authetication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/screens/map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
